ボタンの配置とテキストの色を変更
Tdrj2716/study_app_hackathon pull request #2
Opened 2022-07-02 14:40 UTC by HironoriUchibori

# ボタンの配置とボタンの色，テキストの色を変更しました．
- ボタンの色：Color.fromRGBO(0, 220, 230, 1)
- テキストの色：Color.fromRGBO(130, 120, 100, 1)

![Simulator Screen Shot - iPhone 13 Pro - 2022-07-02 at 23 38 45](https://user-images.githubusercontent.com/106530533/177005220-2d0830ec-e55a-4cbb-bd64-53cdf876193d.png)

2022-07-02 14:58 UTC, Tdrj2716 requested changes
確認しました！修正してpushし直してください！

2022-07-02 14:58 UTC, Tdrj2716 commented on lib/welcome.dart
> +                onPressed: () {},
同じ形状のボタンを使っているので
```dart
Widget _styledButton({Text text, void Function() onPressed}){
  return ElevatedButton(
    child: text,
    style: ElevatedButton.styleFrom(
      primary: Color.fromRGBO(0, 220, 230, 1),
      onPrimary: Color.fromRGBO(130, 120, 100, 1),
    ),
    onPressed: onPressed,
  );
}
```
という感じで共通化して
```dart
children: [_styledButton(text: const Text('ルームを作る'), onPressed: () {}), ...]
```
みたいにしたいです！将来、ボタンのサイズや色を変更する際に、共通化しておけば修正のしやすさが上がります

できれば色も変数として出しておきたいですが、まだあまり固まっていないのでひとまず大丈夫です！

2022-07-03 01:57 UTC, HironoriUchibori commented
# 背景と文字の色を統一色に変更
ボタンの統一についてはまだ変更していません．．
<img width="441" alt="スクリーンショット 2022-07-03 10 55 24" src="https://user-images.githubusercontent.com/106530533/177021440-16a71b27-dc04-4e0a-9fd9-c64604875c3e.png">

2022-07-03 02:14 UTC, Tdrj2716 approved these changes
確認しました！レビュー参考にしてこの後も実装お願いします

2022-07-03 02:14 UTC, Tdrj2716 commented on lib/welcome.dart
> +            //title: Text("ホーム"),
コメントは不要になったら消しておきましょう！

2022-07-03 02:14 UTC, Tdrj2716 commented on lib/welcome.dart
> +                  primary: Color(0xFFD1EEF3),
例えばここの`Color(0xFFD1EEF3)`部分を
```dart
const mainBlue = Color(0xFFD1EEF3);
...
primary: mainBlue,
...
```
みたいにしておくと、
- Colorの色指定でタイポするのを防げる
- 変数がエディタからサジェストされやすい
ので、便利です！今回は速度重視なのでこれで一旦mergeします

2022-07-03 02:17 UTC, Tdrj2716 commented
すいません！conflictしてるので修正してください！

2022-07-03 02:30 UTC, HironoriUchibori commented
# welcome画面にアイコンを追加

アプリのアイコンを追加しましたが，デザイン班が提示したようにAppBarに重ねて表示できていません．

<img width="485" alt="スクリーンショット 2022-07-03 11 28 18" src="https://user-images.githubusercontent.com/106530533/177022118-d05b8b89-4371-42d4-9e10-39f991f3e89a.png">

2022-07-03 02:36 UTC, merged